CREATE SCHEMA IF NOT EXISTS EXEMPLOS;

DROP TABLE IF EXISTS EXEMPLOS.TELEFONE;
DROP TABLE IF EXISTS EXEMPLOS.CLIENTE;
DROP TABLE IF EXISTS EXEMPLOS.ENDERECO;

CREATE TABLE EXEMPLOS.TELEFONE (
  id INT NOT NULL AUTO_INCREMENT,
  codigoPais VARCHAR(2) NOT NULL,
  ddd VARCHAR(2) NOT NULL,
  numero VARCHAR(12) NOT NULL,
  movel INTEGER NOT NULL,
  ativo INTEGER NOT NULL,
  idCliente INT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE EXEMPLOS.ENDERECO (
  id INT NOT NULL AUTO_INCREMENT,
  cep VARCHAR(8) NOT NULL,
  estado VARCHAR(255) NOT NULL,
  cidade VARCHAR(255) NOT NULL,
  bairro VARCHAR(255) NOT NULL,
  rua VARCHAR(255) NOT NULL,
  numero VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE EXEMPLOS.CLIENTE (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  sobrenome VARCHAR(255) NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  idEndereco INT NOT NULL, 
  PRIMARY KEY (id),
  CONSTRAINT id FOREIGN KEY (idEndereco) 
  	REFERENCES exemplos.endereco (id)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT,
  CONSTRAINT constraint_cpf UNIQUE (cpf));